### ISSUE TITLE
При фокусе поднимаем лейбл наверх

### ISSUE THREAD

**Issue by DanilShum** [DanilShum/autocomplete#1]

**Comment by web-crab** [comment]
Лейбл должен уменьшаться и сдвигаться наверх. Сделать это нужно с помощью css transform. Вот статья которая расскажет, с какой скоростью должна происходить анимация и какой ease выбрать.
https://habr.com/ru/post/424383/

**Comment by web-crab** [comment]
Думаю сюда можно добавить и стрелочку. Когда поле сфокусировано - стрелочка синего цвета и перевернута. Стрелочку сделать на css, погугли как делать треугольники
